CREATE TABLE IF NOT EXISTS customer (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS asset (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
customer_id BIGINT NOT NULL,
asset_name VARCHAR(50) NOT NULL,
size DOUBLE NOT NULL,
usable_size DOUBLE NOT NULL,
FOREIGN KEY (customer_id) REFERENCES customer(id)
);